### ISSUE TITLE
Missing pig summoning feature

### ISSUE THREAD

**Issue by fatcerberus** [rhuanjl/SphereLibs#4]
The map engine lacks the ability to summon giant hungry pigs that devour everything in their path (including the player).  If such a feature were implemented then it would be perfect.

Note that this implementation likely requires someone with a great deal of experience in, and I quote, “whatever arcane art it would require to cause computers to spawn enourmous *[sic]* man eating pigs” so it ~~might not be~~ probably isn’t feasible.  But it can’t hurt to ask, right? :smile:

:pig2: :pig_nose:

**Comment by Eggbertx** [comment]
I'll add this to my Sphertomata project when I adapt it to be usable with the map engine.
