### ISSUE TITLE
Bug: Cannot elide unneeded methods from mapScripts

### ISSUE THREAD

**Issue by fatcerberus** [rhuanjl/SphereLibs#5]
Leaving out methods from a map script doesn't seem to work despite there apparently being code to handle this case.  I have a map script that looks like this:

```js
/*
 *  OFF: Puppetmaster  (c) 2018 Fat Cerberus
 *  based on OFF by Mortis Ghost  (c) 2008
 */

import { Music } from 'sphere-runtime';

export const mapScripts =
{
    onEnter(runTime, map)
    {
        Music.play('@/music/emptyWarehouse-out.ogg');
    },
};
```

But the map engine, upon loading the map, immediately crashes with:
```
uncaught JavaScript exception

TypeError: Object doesn't support property or method 'onUpdate'
   at MEngine.prototype.update (@/lib/map-engine/MEngine.mjs:134:9)
   at Anonymous function (@/lib/map-engine/map-engine.mjs:172:13)
```

**Comment by rhuanjl** [comment]
This is a bug I will fix it shortly.

**Comment by rhuanjl** [comment]
Fix is in https://github.com/rhuanjl/SphereLibs/commit/542067dab07b3c44036c1fbe045e14a285ce098a not master branch as want to stack up several changes and test them all before pushing to master.

EDIT: that was not quite right, fix is now in https://github.com/rhuanjl/SphereLibs/commit/61d8938f14f2d47eeb68218607594ca39165f6d5

**Comment by rhuanjl** [comment]
After getting it wrong a ton of times should work now in the tidy branch.

I wish I had tests setup but they would be kinda tricky for this sort of system.

**Comment by fatcerberus** [comment]
It works now when removing onUpdate and onRender from my map scripts so yes, this is fixed.  I’ll close this now.
