### ISSUE TITLE
Feature Request: Global map scripts

### ISSUE THREAD

**Issue by fatcerberus** [rhuanjl/SphereLibs#7]
Feature suggestion to implement global map scripts, so that you can have map scripts that run for any map, in addition to the usual per-map scripts.  This is a similar concept to `SetDefaultMapScript()` in Sphere v1.

The idea I'm thinking of is to implement fade-in and fade-out on any map change.  So you could set up a class to handle fading and then have a global map script that looks something like this:
```js
export const globalMapScripts =
{
    async onEnter() {
        await screenFader.fadeTo(Color.Transparent, 60);  // fade in
    },
    async onExit() {
        await screenFader.fadeTo(Color.Black, 60);  // fade out
    },
};
```

Currently this code would need to go into every map script but it would nicer if the same code could be shared automatically by the map engine.

**Comment by rhuanjl** [comment]
Easy fix will do today.... Haven't done yet with all the other issues - question is where the best place to put these is.

**Comment by rhuanjl** [comment]
Added experimentally in the tidyup branch as MEngine#{onUpdate, onRender, onExit, onEnter}

Simply write over them to set them.

Note:
- onExit and onEnter are promise wrapped so using async functions should work the way you intend.
- onUpdate and onRender are not promised wrapped and will be expected to act synchronously.

**Comment by rhuanjl** [comment]
Merged into master so closing this.
